# champions.py

# Mapping of champions to categories
champion_roles = {

    "Janna": "Enchanter",
    "Lulu": "Enchanter",
    "Yuumi": "Enchanter",
    "Renata Clasc": "Enchanter",
    "Nami": "Enchanter",
    "Milio": "Enchanter",
    "Sona": "Enchanter",
    "Soraka": "Enchanter",
    "Rakan": "Catcher",
    "Bard": "Catcher",
    "Blitzkrank": "Catcher",
    "Morgana": "Catcher",
    "Ivern": "Catcher",
    "Pyke": "Catcher",
    "Thresh": "Catcher",
    "Zyra": "Catcher",
    "Aatrox": "Juggernaut",
    "Volibear": "Juggernaut",
    "Urgot": "Juggernaut",
    "Udyr": "Juggernaut",
    "Trundle": "Juggernaut",
    "Illaoi": "Juggernaut",
    "Darius": "Juggernaut",
    "Dr. Mundo": "Juggernaut",
    "Garen": "Juggernaut",
    "Mordekaiser": "Juggernaut",
    "Nasus": "Juggernaut",
    "Sett": "Juggernaut",
    "Shyvana": "Juggernaut",
    "Yorick": "Juggernaut",
    "Ambessa": "Diver",
    "Xin Zhao": "Diver",
    "Wukong": "Diver",
    "Warwick": "Diver",
    "Vi": "Diver",
    "Jarvan IV": "Diver",
    "Briar": "Diver",
    "Hecarim": "Diver",
    "Camille": "Diver",
    "Elise": "Diver",
    "Irelia": "Diver",
    "Lee Sin": "Diver",
    "Olaf": "Diver",
    "Pantheon": "Diver",
    "Rek'Sai": "Diver",
    "Renekton": "Diver",
    "Hwei": "Artillery",
    "Jayce": "Artillery",
    "Mel": "Artillery",
    "Vel'Coz": "Artillery",
    "Xerath": "Artillery",
    "Ziggs": "Artillery",
    "Ahri": "Burst",
    "Annie": "Burst",
    "Aurora": "Burst",
    "Brand": "Burst",
    "Karma": "Burst",
    "Lissandra": "Burst",
    "Lux": "Burst",
    "Neeko": "Burst",
    "Orianna": "Burst",
    "Seraphine": "Burst",
    "Syndra": "Burst",
    "Twisted Fate": "Burst",
    "Veigar": "Burst",
    "Vex": "Burst",
    "Zoe": "Burst",
    "Anivia": "Battlemage",
    "Aurelion Sol": "Battlemage",
    "Cassiopeia": "Battlemage",
    "Karthus": "Battlemage",
    "Malzahar": "Battlemage",
    "Rumble": "Battlemage",
    "Ryze": "Battlemage",
    "Swain": "Battlemage",
    "Taliyah": "Battlemage",
    "Viktor": "Battlemage",
    "Vladimir": "Battlemage",
    "Akali": "Assassin",
    "Diana": "Assassin",
    "Ekko": "Assassin",
    "Evelynn": "Assassin",
    "Fizz": "Assassin",
    "Kassadin": "Assassin",
    "Katarina": "Assassin",
    "Kha'Zix": "Assassin",
    "Naafiri": "Assassin",
    "Nocturne": "Assassin",
    "Qiyana": "Assassin",
    "Rengar": "Assassin",
    "Shaco": "Assassin",
    "Talon": "Assassin",
    "Zed": "Assassin",
    "Le Blanc": "Assassin",
    "Fiora": "Skirmisher",
    "Gwen": "Skirmisher",
    "Jax": "Skirmisher",
    "Bel'Veth": "Skirmisher",
    "Kayn": "Skirmisher",
    "Kled": "Skirmisher",
    "Lilia": "Skirmisher",
    "Master Yi": "Skirmisher",
    "Nilah": "Skirmisher",
    "Riven": "Skirmisher",
    "Sylas": "Skirmisher",
    "Tryndamere": "Skirmisher",
    "Viego": "Skirmisher",
    "Yasuo": "Skirmisher",
    "Yone": "Skirmisher",
    "Viego": "Skirmisher",
    "Akshan": "Marksman",
    "Aphelios": "Marksman",
    "Ashe": "Marksman",
    "Caitlyn": "Marksman",
    "Corki": "Marksman",
    "Draven": "Marksman", 
    "Ezreal": "Marksman",
    "Jinx": "Marksman",
    "Jhin": "Marksman",
    "Kai'sa": "Marksman",
    "Kalista": "Marksman",
    "Kindred": "Marksman",
    "Kog'Maw": "Marksman",
    "Lucian": "Marksman",
    "Miss Fortune": "Marksman",
    "Samira": "Marksman",
    "Senna": "Marksman",
    "Sivir": "Marksman",
    "Smolder": "Marksman",
    "Tristana":"Marksman",
    "Varus": "Marksman",
    "Vayne": "Marksman",
    "Xayah": "Marksman",
    "Yunara": "Marksman",
    "Zeri": "Marksman",
    "Alistar": "Vanguard",
    "Amumu": "Vanguard",
    "Gragas": "Vanguard",
    "Leona": "Vanguard",
    "Malphite": "Vanguard",
    "Maokai": "Vanguard",
    "Nautilus": "Vanguard",
    "Nunu": "Vanguard",
    "Ornn": "Vanguard",
    "Rammus": "Vanguard",
    "Rell": "Vanguard",
    "Sejuani": "Vanguard",
    "Sion": "Vanguard",
    "Skarner": "Vanguard",
    "Zac": "Vanguard",
    "Braum": "Warden",
    "Galio": "Warden",
    "K'Sante": "Warden",
    "Poppy": "Warden",
    "Shen": "Warden",
    "Tahm Kench": "Warden",
    "Taric": "Warden",
    "Azir": "Specialist",
    "Cho'Gath": "Specialist",
    "Fiddlesticks": "Specialist",
    "Gangplank": "Specialist",
    "Gnar": "Specialist",
    "Graves": "Specialist",
    "Heimerdinger": "Specialist",
    "Kayle": "Specialist",
    "Kennen": "Specialist",
    "Nidalee": "Specialist",
    "Quinn": "Specialist",
    "Singed": "Specialist",
    "Teemo": "Specialist",
    "Zilean": "Specialist"
    
    }

# Function to get the category
def get_category(champion_name):
    return champion_roles.get(champion_name, "Unknown")
